### ISSUE TITLE
Error checking for running containers

### ISSUE THREAD

**Issue by lcarva** [lcarva/osbs-box#29]
```
Traceback (most recent call last):
  File "./osbs-box.py", line 214, in <module>
    parsed.func(parsed)
  File "./osbs-box.py", line 135, in up
    _wait_until_container_is_up('koji-client')
  File "./osbs-box.py", line 56, in _wait_until_container_is_up
    output = _run(cmd, show_print=False)
  File "./osbs-box.py", line 42, in _run
    cmd, proc.returncode))
RuntimeError: Command docker inspect osbsbox_koji-client_1 --format='{{.State.Running}}' failed with exitcode 1
```

However, containers are actually running:
```
$ docker-compose ps
         Name                       Command               State                          Ports                        
----------------------------------------------------------------------------------------------------------------------
osbsbox_koji-builder_1   /usr/local/bin/entrypoint. ...   Up                                                          
osbsbox_koji-client_1    /usr/local/bin/entrypoint. ...   Up                                                          
osbsbox_koji-db_1        docker-entrypoint.sh postgres    Up      5432/tcp                                            
osbsbox_koji-hub_1       /usr/local/bin/entrypoint. ...   Up      443/tcp, 80/tcp, 0.0.0.0:8080->8080/tcp,            
                                                                  0.0.0.0:8083->8083/tcp                              
osbsbox_registry_1       /entrypoint.sh /etc/docker ...   Up      0.0.0.0:5000->5000/tcp                              
osbsbox_shared-data_1    /usr/local/bin/entrypoint. ...   Up      80/tcp                   
```

**Comment by lcarva** [comment]
This has been addressed by: https://github.com/lcarva/osbs-box/pull/36
